version: "2"

services:
  head-server:
    environment:
      DBAPI_HOST: "localhost"
      DBAPI_PORT: "3001"
    build: head-server/
    ports:
      - "5401:3000"

  play-worker:
    environment:
      DB_API_HOST: "head-server"
      DB_API_PORT: "3000"
    build: play-worker/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5402:3000"
